const API_URL = 'https://script.google.com/macros/s/AKfycbynd9zWFineNABPYqmTM4y3X5S6LJ8YBE5-3f5xcTiXbrSWEBIHfjnx2OFaBRYEjC2C/exec';
const state={view:'dashboard',page:1,pageSize:20,search:'',kategori:'',sort:'piutang_desc',cache:new Map()};
const $=id=>document.getElementById(id);
const rupiah=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const compact=v=>{v=Number(v||0);if(v>=1e9)return'Rp'+(v/1e9).toLocaleString('id-ID',{maximumFractionDigits:1})+' M';if(v>=1e6)return'Rp'+(v/1e6).toLocaleString('id-ID',{maximumFractionDigits:1})+' jt';if(v>=1e3)return'Rp'+(v/1e3).toLocaleString('id-ID',{maximumFractionDigits:0})+' rb';return rupiah(v)};
const num=v=>new Intl.NumberFormat('id-ID').format(Number(v||0));
const pct=v=>Number(v||0).toLocaleString('id-ID',{maximumFractionDigits:1})+'%';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(action,params={}){const u=new URL(API_URL);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)});const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!r.ok||j.success===false)throw Error(j?.error?.message||`HTTP ${r.status}`);return j}
function status(ok=true,text='Live API'){$('api-status').innerHTML=`<span class="status-dot" style="background:${ok?'var(--green)':'var(--red)'}"></span><span>${esc(text)}</span>`}
function toast(t){const e=$('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.add('hidden'),2600)}
function fail(prefix,e){status(false,'API unavailable');toast(`${prefix}: ${e.message}`)}
function switchView(view){state.view=view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`${view}-view`).classList.remove('hidden');$('page-title').textContent={dashboard:'Customer Intelligence',customers:'Customers',ranking:'Ranking',branch:'Branch'}[view]||'Customer Intelligence';$('sidebar').classList.remove('open');if(view==='dashboard')loadDashboard();if(view==='customers')loadCustomers();if(view==='ranking')loadRanking();if(view==='branch')loadBranch()}
function bind(root){root.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>openCustomer(b.dataset.customer))}
async function loadDashboard(){try{const r=await api('analytics');const a=r.analytics||{},s=r.summary||{},types=a.by_type||{};const total=a.total_piutang||s.total_piutang||0;const tx=a.jumlah_transaksi||s.jumlah_transaksi||0;const customers=a.jumlah_customer||s.jumlah_customer||0;$('kpi-customers').textContent=num(customers);$('kpi-category').textContent='Semua customer aktif';$('kpi-piutang').textContent=compact(total);$('kpi-piutang-full').textContent=rupiah(total);$('kpi-active').textContent=num(tx);$('kpi-raw').textContent='Piutang aktif teragregasi';$('kpi-pages').textContent='V3';$('kpi-complete').textContent='Index tervalidasi';renderTypeDistribution(types);renderProfile(a.customer_profile||{});renderAnalyticsInsight(types,total);renderTopCustomers(a.top_customers||[],total);status(true,'Live API')}catch(e){fail('Analytics gagal dimuat',e)}}
function renderTypeDistribution(types){const order=['TOKO','CABANG','PARTAI','LAIN'];$('type-distribution').innerHTML=order.map(t=>{const x=types[t]||{};return`<div class="type-row"><div class="type-head"><strong>${t}</strong><span>${num(x.jumlah_customer||0)} customer · ${pct(x.persentase_piutang)} piutang</span></div><div class="type-bar"><span style="width:${Math.min(100,Number(x.persentase_piutang||0))}%"></span></div><div class="type-foot"><span>${num(x.jumlah_transaksi||0)} transaksi</span><strong>${rupiah(x.total_piutang||0)}</strong></div></div>`}).join('')}
function renderProfile(p){$('profile-metrics').innerHTML=[['Single type',p.single_type],['Multi type',p.multi_type],['2 tipe',p.two_type],['3–4 tipe',(p.three_type||0)+(p.four_type||0)]].map(x=>`<div class="mini-metric"><span>${x[0]}</span><strong>${num(x[1]||0)}</strong></div>`).join('')}
function renderAnalyticsInsight(types,total){const toko=types.TOKO||{},cab=types.CABANG||{};$('business-insight').innerHTML=`<div class="insight-card"><div class="insight-label">Portfolio insight</div><div class="insight-title">TOKO adalah sumber utama piutang</div><div class="insight-copy">Penjualan TOKO menyumbang ${pct(toko.persentase_piutang)} dari total outstanding, sedangkan CABANG menyumbang ${pct(cab.persentase_piutang)}. Gunakan distribusi ini sebagai dasar prioritas collection dan credit control.</div><div class="progress"><span style="width:${Math.min(100,Number(toko.persentase_piutang||0))}%"></span></div><div class="insight-stat"><span>${rupiah(toko.total_piutang||0)} dari ${rupiah(total)}</span><strong>${pct(toko.persentase_piutang)}</strong></div><div class="insight-metrics"><div class="mini-metric"><span>Customer TOKO</span><strong>${num(toko.jumlah_customer||0)}</strong></div><div class="mini-metric"><span>Customer CABANG</span><strong>${num(cab.jumlah_customer||0)}</strong></div></div></div>`}
function renderTopCustomers(items,total){$('top-debt-list').innerHTML=items.slice(0,5).map((x,i)=>{const sh=Number(x.total_piutang||0)/Number(total||1)*100;return`<div class="rank-row"><div class="rank-number">${i+1}</div><div class="rank-main"><button class="customer-link rank-name" data-customer="${esc(x.pelanggan)}">${esc(x.pelanggan)}</button><div class="rank-meta">${num(x.jumlah_transaksi)} transaksi · ${pct(sh)}</div></div><div class="rank-value"><strong>${compact(x.total_piutang)}</strong><small>${rupiah(x.total_piutang)}</small></div></div>`}).join('')||'<div class="empty">Belum ada data.</div>';bind($('top-debt-list'))}
function customerTable(items){return`<table class="data-table"><thead><tr><th>Customer</th><th>Kategori</th><th class="number">Transaksi</th><th class="number">Piutang</th><th>Tipe</th></tr></thead><tbody>${items.map(x=>`<tr><td><button class="customer-link" data-customer="${esc(x.pelanggan)}">${esc(x.pelanggan)}</button></td><td>${esc(x.kategori||'—')}</td><td class="number">${num(x.jumlah_transaksi_aktif??x.jumlah_transaksi)}</td><td class="number"><strong>${compact(x.total_piutang)}</strong></td><td>${esc(x.transaction_types?.join(', ')||'—')}</td></tr>`).join('')}</tbody></table>`}
async function loadCustomers(){try{const r=await api('customers',{page:state.page,page_size:state.pageSize,search:state.search,kategori:state.kategori,sort:state.sort});const d=r.data||{};$('customer-table').innerHTML=d.items?.length?customerTable(d.items):'<div class="empty">Customer tidak ditemukan.</div>';bind($('customer-table'));renderPagination(d.pagination);status(true,'Live API')}catch(e){fail('Customer gagal dimuat',e)}}
function renderPagination(p){if(!p){$('customer-pagination').innerHTML='';return}$('customer-pagination').innerHTML=`<div>Halaman <strong>${p.page}</strong>/<strong>${p.total_page}</strong> · ${num(p.total)} customer</div><div class="pagination-actions"><button class="page-button" id="prev-page" ${p.has_previous?'':'disabled'}>← Sebelumnya</button><button class="page-button" id="next-page" ${p.has_next?'':'disabled'}>Berikutnya →</button></div>`;$('prev-page').onclick=()=>{if(p.has_previous){state.page--;loadCustomers()}};$('next-page').onclick=()=>{if(p.has_next){state.page++;loadCustomers()}}}
async function loadRanking(){try{const r=await api('analytics');const items=r.analytics?.top_customers||[];$('ranking-table').innerHTML=`<table class="data-table"><thead><tr><th>#</th><th>Customer</th><th>Kategori</th><th class="number">Transaksi</th><th class="number">Piutang</th><th>Tipe</th></tr></thead><tbody>${items.map(x=>`<tr><td class="rank-table-number">${x.ranking}</td><td><button class="customer-link" data-customer="${esc(x.pelanggan)}">${esc(x.pelanggan)}</button></td><td>${esc(x.kategori||'—')}</td><td class="number">${num(x.jumlah_transaksi)}</td><td class="number"><strong>${rupiah(x.total_piutang)}</strong></td><td>${esc(x.transaction_types?.join(', ')||'—')}</td></tr>`).join('')}</tbody></table>`;bind($('ranking-table'));status(true,'Live API')}catch(e){fail('Ranking gagal dimuat',e)}}
async function loadBranch(){try{const r=await api('branch',{kategori:'CABANG'});const d=r.data||{};$('branch-kpis').innerHTML=`<article class="kpi-card"><span>Customer</span><strong>${num(d.jumlah_customer)}</strong><small>CABANG</small></article><article class="kpi-card"><span>Piutang</span><strong>${compact(d.total_piutang)}</strong><small>${rupiah(d.total_piutang)}</small></article><article class="kpi-card"><span>Transaksi</span><strong>${num(d.jumlah_transaksi_aktif)}</strong><small>${num(d.total_raw)} raw</small></article><article class="kpi-card"><span>Pages</span><strong>${num(d.jumlah_page)}</strong><small>Complete</small></article>`;$('branch-table').innerHTML=d.customers?.length?customerTable(d.customers):'<div class="empty">Belum ada data branch.</div>';bind($('branch-table'));status(true,'Live API')}catch(e){fail('Branch gagal dimuat',e)}}
async function openCustomer(name){const drawer=$('customer-drawer');drawer.classList.add('open');$('drawer-backdrop').classList.remove('hidden');$('drawer-name').textContent=name;$('drawer-content').innerHTML='<div class="loading-block"></div>';try{let d=state.cache.get(name);if(!d){d=(await api('customer',{pelanggan:name})).data;state.cache.set(name,d)}const types=d.type_profile||{};$('drawer-content').innerHTML=`<div class="detail-kpi"><span>Total Piutang</span><strong>${rupiah(d.total_piutang)}</strong></div><div class="detail-grid"><div class="detail-kpi"><span>Transaksi</span><strong>${num(d.jumlah_transaksi_aktif??d.jumlah_transaksi)}</strong></div><div class="detail-kpi"><span>Kategori</span><strong>${esc(d.kategori||'—')}</strong></div></div><div class="integrity"><h4>Transaction Profile</h4>${Object.entries(types).map(([k,v])=>`<div class="check">${esc(k)} · ${num(v.jumlah_transaksi)} transaksi · ${rupiah(v.total_piutang)}</div>`).join('')||'<div class="check">Profile belum tersedia</div>'}</div>`}catch(e){$('drawer-content').innerHTML=`<div class="empty">Gagal mengambil detail customer.<br>${esc(e.message)}</div>`}}
function closeCustomer(){$('customer-drawer').classList.remove('open');$('drawer-backdrop').classList.add('hidden')}
let timer;$('customer-search').oninput=e=>{state.search=e.target.value.trim();state.page=1;clearTimeout(timer);timer=setTimeout(loadCustomers,300)};$('customer-category').onchange=e=>{state.kategori=e.target.value;state.page=1;loadCustomers()};$('customer-sort').onchange=e=>{state.sort=e.target.value;state.page=1;loadCustomers()};$('refresh-dashboard').onclick=loadDashboard;$('refresh-customers').onclick=loadCustomers;$('refresh-ranking').onclick=loadRanking;$('refresh-branch').onclick=loadBranch;$('drawer-close').onclick=closeCustomer;$('drawer-backdrop').onclick=closeCustomer;$('mobile-menu').onclick=()=> $('sidebar').classList.toggle('open');document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>switchView(x.dataset.view));document.onkeydown=e=>{if(e.key==='Escape')closeCustomer()};loadDashboard();
